# These are supported funding model platforms

github: PonomareVlad
patreon: PonomareVlad
open_collective: PonomareVlad
ko_fi: PonomareVlad
tidelift: PonomareVlad
community_bridge: PonomareVlad
liberapay: PonomareVlad
issuehunt: PonomareVlad
lfx_crowdfunding: PonomareVlad
polar: PonomareVlad
buy_me_a_coffee: PonomareVlad
thanks_dev: PonomareVlad
custom: https://PonomareVlad.ru/donate
